### PR TITLE
Common friends count in suggestion list

### PR DESCRIPTION
**Pull request by ikwattro**
Hi,

This simple change adds the possibility to show common friendships count in the suggestions list.
- Modified the Cypher query to count friendship similarities
- Added a commonFriends property to the user model

NB: I'm not really familiar with Slim and Mustache, so I would prefer to pass the commonFriends to the view rather than setting it as User property in the model, feel free to push against the P.R.

Chris

### CODE REVIEW

**Comment by jeremykendall** [comment]
Awesome PR, @ikwattro. One thing, it looks like `UserService::fromArray()` didn't get committed.  This is what I get when I hit `/friends`:

screenshot 2014-10-29 21 51 13

**Comment by ikwattro** [comment]
This is fixed now, sorry I copied code from the VM, which do not use current development version.

Also, I can see queries where `START` is still used and some where the label is not always used.

Doing such queries, as of Neo4j 2.1.5 and upcoming 2.2, is a bit deprecated.

Would you be happy if I change them ?

**Comment by ikwattro** [comment]
Current preview : 

Imgur

**Comment by jeremykendall** [comment]
> This is fixed now, sorry I copied code from the VM, which do not use current development version.

Oh. That's not good. I need to fix that.

> Also, I can see queries where START is still used and some where the label is not always used.
> 
> Doing such queries, as of Neo4j 2.1.5 and upcoming 2.2, is a bit deprecated.
> 
> Would you be happy if I change them ?

That would be awesome. If you're going to do some query refactoring, would you mind doing it in a separate pull request?

Thanks!

**Comment by ikwattro** [comment]
Yes of course, I did another PR already

**Pull request merged**
