### PR TITLE
refactored app bootstrap

### PR DESCRIPTION
**Pull request by ikwattro**
What do you think about this kind of index.php refactoring ?

Also I added an index_dev.php that can only be run in local env.

@guillermoandrae pls check boostrap phpunit to see if you're ok

### CODE REVIEW

**Comment by jeremykendall** [comment]
Reviewing ...

**Comment by jeremykendall** [comment]
_My subjective opinion follows_: This looks like an interesting mix of Symfony2/Silex design philosophy while staying within the Slim paradigm. I'm not 100% sold, but I'm kinda liking it.

@guillermoandrae, I know you have a good amount of Slim experience. Do you have any thoughts?

**Comment by jeremykendall** [comment]
Two thoughts:
- The Graph Kit is an example application. It should _never_ be deployed to production. That makes me think this is overkill _in this specific context_.
- There are some abstractions intentionally left out of the Graph Kit in order to make it more approachable to developers at beginning and intermediate levels. I'm concerned that the `index_dev.php` script _might_ be more of a distraction than a help.

Your thoughts?

**Comment by guillermoandrae** [comment]
Breaking the `Slim` configuration out into `app.php` is perfect -- we need for it to be that way in order to get the tests working. I have to agree that the `index_dev.php` doesn't seem necessary for this app. I think it may be worth it to move lines 15-17 & 19-24 into the `index.php` file, though.

**Comment by jeremykendall** [comment]
@guillermoandrae 

> I think it may be worth it to move lines 15-17 & 19-24 into the index.php file, though.

Will you post a link to those lines? Not sure which lines you're talking about.

**Comment by ikwattro** [comment]
Maybe having the possibility to get a more debugging level based on a query param then?

index.php ? debug= true which will be allowed only in local env

**Comment by ikwattro** [comment]
Also i did internally some tests to bootstrap the slim app in the tests.

currently i think it is very hard to test and to modify the client in order to use the mock for e.g.

**Comment by ikwattro** [comment]
@jeremykendall @guillermoandrae Any update on this one ? Is there something I have to do before merge ?

**Comment by jeremykendall** [comment]
@guillermoandrae ???

I'll review and comment later tonight or tomorrow. I haven't forgotten about this, but I'm feeling ill and heading home shortly. Sorry for the hold up.

**Comment by guillermoandrae** [comment]
WIll get to this tonight, fellas.

**Comment by ikwattro** [comment]
;-)

**Comment by jeremykendall** [comment]
My thoughts:
- I want a single entry point to the application, so I would prefer to not add `index_dev.php`
- Since this app is intended to be used as a sample app only, it probably makes sense to change the default environment from `production` to `development` (which matches the [default Slim setting](http://docs.slimframework.com/#Application-Settings))
- We should use the Slim application mode configuration feature for things like `error_reporting` in the `development` environment:

```
// Only invoked if mode is "development"
$app->configureMode('development', function () {
    error_reporting(-1);
    ini_set('display_errors', TRUE);
    ini_set('display_startup_errors', TRUE);
});
```
- Environment configuration (beyond the ini settings mentioned above) should be handled with a `/config/{environment}.php` file, where the name of the file matches the environment set in `SLIM_MODE`
  - A test environment could then be configured with `/config/test.php` where `SLIM_MODE` is set to `test`
  - This allows all application code to remain the same across environments

With all of that in mind, do we even need to break `/public/index.php` out into `/src/app.php`?

My above comments still don't address @ikwattro's concerns here:

> Also i did internally some tests to bootstrap the slim app in the tests.
> 
> currently i think it is very hard to test and to modify the client in order to use the mock for e.g.

Unless I'm mistaken (@guillermoandrae, correct me if I'm wrong) , I think the plan is to use [Slim Test Helpers](https://github.com/there4/slim-test-helpers) library to aid in testing the Slim application.

**Comment by guillermoandrae** [comment]
Forgot you were waiting for my thoughts here, @jeremykendall. 

Yes, we're using [Slim Test Helpers](http://github.com/there4/slim-test-helpers).

I've always seen a `bootstrap.php` file used as the entry point for automated testing, and would advise against deviating from that unless there's a good reason. While the configuration of the Slim object can be set up the way you're suggesting, I still recommend the use of separate boostrap files for different application contexts. And the use of a bootstrap file for tests requires us to break out the instantiation of the Slim object into another file so that both the web app's bootstrap and the test suite's bootstrap. Again, that config can still be constructed in the way you're suggesting (`config/test.php`).

**Comment by jeremykendall** [comment]
`bootstrap.php` good, but I'd like to remove `index_dev.php`. @ikwattro, would you remove `index_dev.php` (or do you mind if I do so?). I'll merge right away as soon as that's done.

**Comment by jeremykendall** [comment]
> I've always seen a bootstrap.php file used as the entry point for automated testing, and would advise against deviating from that unless there's a good reason.

Agree completely. I didn't mean to convey we should remove that.

**Comment by ikwattro** [comment]
@jeremykendall I'm happy you do it ;-)

**Pull request merged**
